### ISSUE TITLE
setup_raspberrypi_sd.sh hardcoded to /dev/sdb ? 

### ISSUE THREAD

**Issue by kelson42** [kiwix/plug#6]
Hi - first - thanks SO MUCH for all the work on Kiwix. It's a brilliant idea, exceedingly well executed.

Just wondering, the end of setup_raspberrypi_sd.sh uses dd to copy the raspbian image to the sd card called $DEVICE - but it then proceeds to try to format the rest of the device /dev/sdb{1,4}. If you're running all this on a standalone linux box, sdb might not be the device you want, surely?

I'm likely missing something, but I'd have thought some variant of $DEVICE would be more appropriate than /dev/sdb?

Thanks though!

First reported at https://sourceforge.net/p/kiwix/feature-requests/975/

**Comment by kelson42** [comment]
This is absolutely true.

**Comment by qpkorr** [comment]
At the feature request page you mentioned a patch... I've actually made a number of - changes - (to me improvements) to the scripts.  In some cases I didn't understand why certain things were necessary (so my removal of them may be inappropriate for others though they seemed ok for me) - in other cases I just felt things could be done better (eg reduce code duplication when installing packages).  
Thus far I've just cloned your repo, made changes and checked them in to my local master - but I presume I could work out how to move them to a branch and then put them on a fork for your perusal. Any interest?

**Comment by kelson42** [comment]
@qpkorr Nice. I'm confident that most of your changes - if not all - are improvements to kiwix-plug. I would like therefore to see them merged here. I propose to just give you a developer status so you can merge them by yourself. The only think I would like, is that you use the "pull request" approach for each of the fix and give me a few days to have a look to each of them. Except if there is a problem on my side, you could then merge them after a few days (no feedback means approval). Would you volunteer to do that, that way?

**Comment by qpkorr** [comment]
@kelson42 It's about now that I wish I'd checked them in more incrementally... anyway, guess we'll see how we go.  I don't have my changes in front of me and most were done a while ago - but a key change I do remember was that the existing code seemed to do the indexing itself.  If I recall correctly, a) this is very slow, and b) it's now very easy to simply download the pre-indexed ZIM files so this isn't necessary - at least for Wikipedia, which was the only one I was after at the time.  Any thoughts on this?  
Anyway, I'll go back to my code and see if it needs some tidying/commenting, and finally learn more about pull requests and the wonderful world of github :)

**Comment by kelson42** [comment]
@qpkorr thx, I just have sent you an invitation to join the team. Please do not make your life too complicated. Clean your code and if possible split it in a few blocks/commits so it still is re-viewable.

**Comment by qpkorr** [comment]
@kelson42 Will do my best.  On closer inspection - I note that
a) my target platform was purely a raspberry pi, not a plug - so there was lots of code I simply didn't need, and
b) In many cases I chose to comment out the original code, noting why, and adding my own versions instead.  I guess I'll try to do something more in line with the use of version control, now ;)

As such... to be honest - it may make more sense if I just made a fork of your code and committed my changes to that, so that people could more easily use whichever version suited them better (if they bothered to look further than yours).  Anyway - I'll try to split up my changes, but I'm not being modest when I say that many of them are probably worthless to you!!

**Comment by qpkorr** [comment]
Heavens I really butchered things at times... eg - when I had people directed to the generic "Pick your wiki" landing page, my non-tech friends said they didn't know what to do - so since my goal was wikipedia, I changed things to take them directly to wikipedia (though also to make links from wikipedia to wiktionary work, I think).  Again - not what you want.....!

**Comment by qpkorr** [comment]
Hi @kelson42. Ok, I've split up my changes as best I can, forked your repo, and committed my changes on a branch.  Realistically - maybe 10-20% of my changes might be useful?  My goal has been to get a raspberry pi-based system only - and I'm not sure to what extent the same code base can be used for both the pi and a plug (I know almost nothing about the plug).  Anyway - I suggest you have a look at my stuff and let me know if you want any of it.  If nothing else, it can be available for others for reference now.  https://github.com/qpkorr/plug/tree/qpkorr_rpi  Cheers, John

**Comment by kelson42** [comment]
Hi @qpkorr Thank you for your branch. I had a look in details but you are pretty right: lots of stuff and lots of stuff hardcoded/spectific to your project. It's impossible to merge it as this. I will keep this ticket open. We currently lead an experimentation which should lead to have a new version of kiwix-plug which should be a lot easier to run (everybody could do it)... let see if that work and if this will outdate kiwix-plug.

**Comment by kelson42** [comment]
Successor of Kiwix-Plug, Kiwix-Hotspot has a full control over partitions. This bug is not valid anymore.
